version: '3.8'
services:
  vprodb:
    build: 
      context: ./Docker-files/db
    image: nandinips1624/vprofiledb
    container_name: vproddb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass  
    
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"    

  vproapp:
    build: 
      context: ./Docker-files/app
    image: nandinips1624/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vprodappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
      context: ./Docker-files/web
    image: nandinips1624/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vprodappdata: {}
